import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

const IdiomaContext = createContext();

const traducciones = {
  es: {
    tema: 'Tema',
    claro: 'Claro',
    oscuro: 'Oscuro',
    idioma: 'Idioma',
    porFavorIngresaCorreo: 'Por favor ingresa tu correo',
    porFavorCompletaCampos: 'Por favor completa todos los campos',
    correoContrasenaIncorrectos: 'Correo o contraseña incorrectos',
    inicioSesion: 'Iniciar Sesión',
    contrasena: 'Contraseña',
    iniciaSesion: 'Inicia sesión',
    olvidasteContrasena: '¿Olvidaste tu contraseña?',
    bienvenida: '¡Bienvenido!',
    seleccionaOpcion: 'Por favor selecciona una opción',
    bienvenido: 'Bienvenido',
    controlesMes: 'Controles del mes',
    estadisticas: 'Estadísticas',
    configuracion: 'Configuración',
    preferencias: 'Preferencias',
    notificaciones: 'Notificaciones',
    notiEmail: 'Notificaciones por correo',
    notiPush: 'Notificaciones push',
    cargando: 'Cargando...',
    realizados: 'Realizados',
    pendientes: 'Pendientes',
    EstadisticasControles: 'Estadísticas de Controles',
    GraficoRealizadosPendientes: 'Gráfico Realizados / Pendientes',
    GraficoTopPacientes: 'Gráfico Top Pacientes',
    tuRol: 'Tu rol es',                 
    noAsignado: 'No asignado',          
    totalControles: 'Total controles',
    controlesPorMes: 'Controles por mes',
    recuperar: 'Recuperar',
    correoRecuperacionEnviado: 'Correo de recuperación enviado',
    errorEnviarCorreo: 'Error al enviar correo',
    correoElectronico: 'Correo electrónico',
    enviarRecuperacion: 'Enviar recuperación',
    recordasteContrasena: '¿Recordaste tu contraseña?',
    iniciarSesion: 'Iniciar sesión',
    pacientes: 'Pacientes',
    agregarPaciente: 'Agregar paciente',
    editar: 'Editar',
    eliminar: 'Eliminar',
    rut: 'RUT',
    edad: 'Edad',
    confirmarEliminarPaciente: '¿Estás seguro de que deseas eliminar este paciente?',
    errorEliminarPaciente: 'Error al eliminar paciente',
    errorCargandoPacientes: 'Error al cargar pacientes',
    nuevoPaciente: 'Nuevo paciente',
    editarPaciente: 'Editar paciente',
    nombre: 'Nombre',
    todosCamposObligatorios: 'Todos los campos son obligatorios',
    edadNumeroValido: 'La edad debe ser un número válido mayor o igual a cero',
    errorGuardarPaciente: 'Error al guardar paciente',
    pacienteNoEncontrado: 'Paciente no encontrado',
    errorCargarPaciente: 'Error al cargar paciente',
    guardarCambios: 'Guardar cambios',    
    cargandoPaciente: 'Cargando paciente...',
    detallePaciente: 'Detalle del Paciente',
    volverPacientes: 'Volver a Pacientes',
    marcarRealizado: 'Marcar como realizado',
    desmarcar: 'Desmarcar como realizado',
    agendaControles: 'Agenda de Controles',
    agregarControl: 'Agregar controles',
    editarControl: 'Editar control',
    paciente: 'Paciente',
    seleccionePaciente: 'Seleccione un paciente',
    fecha: 'Fecha',
    realizado: 'Realizado',
    cancelar: 'Cancelar',
    errorActualizarControl: 'Error al actualizar control',
    errorEliminarControl: 'Error al eliminar control',
    confirmarEliminarControl: '¿Estás seguro de que deseas eliminar este control?',
    controlNoEncontrado: 'Control no encontrado',
    detalleControl: 'Detalle del Control',
    si: 'Sí',
    no: 'No',
    observaciones: 'Observaciones',
    volverAgenda: 'Volver a Agenda',
    cerrarSesion: 'Cerrar sesión',
  },
  en: {
    tema: 'Theme',
    claro: 'Light',
    oscuro: 'Dark',
    idioma: 'Language',
    porFavorIngresaCorreo: 'Please enter your email',
    correoRecuperacionEnviado: 'Password recovery email sent',
    errorEnviarCorreo: 'Error sending email',
    porFavorCompletaCampos: 'Please fill in all fields',
    correoContrasenaIncorrectos: 'Email or password incorrect',
    inicioSesion: 'Login',
    correoElectronico: 'Email',
    contrasena: 'Password',
    enviarRecuperacion: 'Send recovery',
    iniciarSesion: 'Log in',
    recordasteContrasena: 'Did you remember your password?',
    iniciaSesion: 'Log in',
    olvidasteContrasena: 'Forgot your password?',
    recuperar: 'Recover',
    bienvenida: 'Welcome!',
    seleccionaOpcion: 'Please select an option',
    cerrarSesion: 'Log out',
    bienvenido: 'Welcome',
    pacientes: 'Patients',
    controlesMes: 'Monthly check-ups',
    estadisticas: 'Statistics',
    configuracion: 'Settings',
    preferencias: 'Preferences',
    notificaciones: 'Notifications',
    notiEmail: 'Email notifications',
    notiPush: 'Push notifications',
    cargando: 'Loading...',
    realizados: 'Completed',
    pendientes: 'Pending',
    EstadisticasControles: 'Check-up Statistics',
    GraficoRealizadosPendientes: 'Completed / Pending Chart',
    GraficoTopPacientes: 'Top Patients Chart',
    tuRol: 'Your role is',
    noAsignado: 'Not assigned',
    totalControles: 'Total check-ups',
    controlesPorMes: 'Check-ups by month',
    agregarPaciente: 'Add patient',
    editar: 'Edit',
    eliminar: 'Delete',
    rut: 'RUT',
    edad: 'Age',
    confirmarEliminarPaciente: 'Are you sure you want to delete this patient?',
    errorEliminarPaciente: 'Error deleting patient',
    errorCargandoPacientes: 'Error loading patients',
    nuevoPaciente: 'New patient',
    editarPaciente: 'Edit patient',
    nombre: 'Name',
    todosCamposObligatorios: 'All fields are required',
    edadNumeroValido: 'Age must be a valid number greater than or equal to zero',
    errorGuardarPaciente: 'Error saving patient',
    pacienteNoEncontrado: 'Patient not found',
    errorCargarPaciente: 'Error loading patient',
    guardarCambios: 'Save changes',
    cargandoPaciente: 'Loading patient...',
    detallePaciente: 'Patient Details',
    volverPacientes: 'Back to Patients',
    marcarRealizado: 'Mark as completed',
    desmarcar: 'Unmark as completed',
    agendaControles: 'Check-up Schedule',
    agregarControl: 'Add check-up',
    editarControl: 'Edit check-up',
    paciente: 'Patient',
    seleccionePaciente: 'Select a patient',
    fecha: 'Date',
    realizado: 'Completed',
    cancelar: 'Cancel',
    errorActualizarControl: 'Error updating check-up',
    errorEliminarControl: 'Error deleting check-up',
    confirmarEliminarControl: 'Are you sure you want to delete this check-up?',
    controlNoEncontrado: 'Check-up not found',
    detalleControl: 'Check-up Details',
    si: 'Yes',
    no: 'No',
    observaciones: 'Observations',
    volverAgenda: 'Back to Schedule',
    
  },
  fr: {
    tema: 'Thème',
    claro: 'Clair',
    oscuro: 'Sombre',
    idioma: 'Langue',
    porFavorIngresaCorreo: 'Veuillez entrer votre e-mail',
    correoRecuperacionEnviado: 'E-mail de récupération envoyé',
    errorEnviarCorreo: 'Erreur lors de l\'envoi de l\'e-mail',
    porFavorCompletaCampos: 'Veuillez remplir tous les champs',
    correoContrasenaIncorrectos: 'E-mail ou mot de passe incorrect',
    inicioSesion: 'Connexion',
    correoElectronico: 'E-mail',
    contrasena: 'Mot de passe',
    enviarRecuperacion: 'Envoyer la récupération',
    iniciarSesion: 'Se connecter',
    recordasteContrasena: 'Vous vous souvenez de votre mot de passe ?',
    iniciaSesion: 'Se connecter',
    olvidasteContrasena: 'Mot de passe oublié ?',
    recuperar: 'Récupérer',
    bienvenida: 'Bienvenue !',
    seleccionaOpcion: 'Veuillez sélectionner une option',
    cerrarSesion: 'Se déconnecter',
    bienvenido: 'Bienvenue',
    pacientes: 'Patients',
    controlesMes: 'Contrôles du mois',
    estadisticas: 'Statistiques',
    configuracion: 'Configuration',
    preferencias: 'Préférences',
    notificaciones: 'Notifications',
    notiEmail: 'Notifications par e-mail',
    notiPush: 'Notifications push',
    cargando: 'Chargement...',
    realizados: 'Réalisés',
    pendientes: 'En attente',
    EstadisticasControles: 'Statistiques des contrôles',
    GraficoRealizadosPendientes: 'Graphique Réalisés / En attente',
    GraficoTopPacientes: 'Graphique des principaux patients',
    tuRol: 'Votre rôle est',
    noAsignado: 'Non assigné',
    totalControles: 'Total des contrôles',
    controlesPorMes: 'Contrôles par mois',
    agregarPaciente: 'Ajouter un patient',
    editar: 'Éditer',
    eliminar: 'Supprimer',
    rut: 'RUT',
    edad: 'Âge',
    confirmarEliminarPaciente: 'Êtes-vous sûr de vouloir supprimer ce patient ?',
    errorEliminarPaciente: 'Erreur lors de la suppression du patient',
    errorCargandoPacientes: 'Erreur lors du chargement des patients',
    nuevoPaciente: 'Nouveau patient',
    editarPaciente: 'Éditer le patient',
    nombre: 'Nom',
    todosCamposObligatorios: 'Tous les champs sont obligatoires',
    edadNumeroValido: 'L\'âge doit être un nombre valide supérieur ou égal à zéro',
    errorGuardarPaciente: 'Erreur lors de l\'enregistrement du patient',
    pacienteNoEncontrado: 'Patient non trouvé',
    errorCargarPaciente: 'Erreur lors du chargement du patient',
    guardarCambios: 'Enregistrer les modifications',
    cargandoPaciente: 'Chargement du patient...',
    detallePaciente: 'Détails du patient',
    volverPacientes: 'Retour aux patients',
    marcarRealizado: 'Marquer comme réalisé',
    desmarcar: 'Décocher réalisé',
    agendaControles: 'Agenda des contrôles',
    agregarControl: 'Ajouter des contrôles',
    editarControl: 'Éditer le contrôle',
    paciente: 'Patient',
    seleccionePaciente: 'Sélectionnez un patient',
    fecha: 'Date',
    realizado: 'Réalisé',
    cancelar: 'Annuler',
    errorActualizarControl: 'Erreur lors de la mise à jour du contrôle',
    errorEliminarControl: 'Erreur lors de la suppression du contrôle',
    confirmarEliminarControl: 'Êtes-vous sûr de vouloir supprimer ce contrôle ?',
    controlNoEncontrado: 'Contrôle non trouvé',
    detalleControl: 'Détails du contrôle',
    si: 'Oui',
    no: 'Non',
    observaciones: 'Observations',
    volverAgenda: 'Retour à l\'agenda',

  },
};

export const IdiomaProvider = ({ children }) => {
  const [idioma, setIdioma] = useState('es');

  useEffect(() => {
    const guardado = localStorage.getItem('idiomaApp');
    if (guardado && traducciones[guardado]) {
      setIdioma(guardado);
    }
  }, []);

  const cambiarIdioma = useCallback((nuevo) => {
    if (traducciones[nuevo]) {
      setIdioma(nuevo);
      localStorage.setItem('idiomaApp', nuevo);
    }
  }, []);

  const t = useCallback((clave) => {
    return traducciones[idioma]?.[clave] || clave;
  }, [idioma]);

  const value = useMemo(() => ({
    idioma,
    cambiarIdioma,
    t,
  }), [idioma, cambiarIdioma, t]);

  return (
    <IdiomaContext.Provider value={value}>
      {children}
    </IdiomaContext.Provider>
  );
};

export const useIdioma = () => useContext(IdiomaContext);
